{
  config,
  pkgs,
  inputs,
  ...
}: {
  imports = [
    ./common/hyprpanel.nix
    ./common/hyprland.nix
  ];
  nixpkgs = {
    config = {
      allowUnfree = true;
      allowUnfreePredicate = _: true;
    };
  };
  # Home Manager needs a bit of information about you and the
  # paths it should manage.
  home.username = "roberte777";
  home.homeDirectory = "/home/roberte777";
  news.display = "silent";

  home.sessionVariables = {
    WLR_NO_HARDWARE_CURSORS = "1";
    NIXOS_OZONE_WL = "1";
  };

  # wayland.windowManager.hyprland = {
  #   enable = true;
  #   plugins = [inputs.split-monitor-workspaces.packages.${pkgs.system}.split-monitor-workspaces];
  #   extraConfig = ''
  #     # #######################################################################################
  #     # AUTOGENERATED HYPR CONFIG.
  #     # PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
  #     # OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
  #     # #######################################################################################
  #
  #     # autogenerated = 1 # remove this line to remove the warning
  #
  #     # This is an example Hyprland config file.
  #     # Refer to the wiki for more information.
  #     # https://wiki.hyprland.org/Configuring/Configuring-Hyprland/
  #
  #     # Please note not all available settings / options are set here.
  #     # For a full list, see the wiki
  #
  #     # You can split this configuration into multiple files
  #     # Create your files separately and then link them to this file like this:
  #     # source = ~/.config/hypr/myColors.conf
  #
  #
  #     ################
  #     ### MONITORS ###
  #     ################
  #
  #     # See https://wiki.hyprland.org/Configuring/Monitors/
  #     #monitor=,preferred,auto,auto
  #     source = ~/.config/hypr/monitors.conf
  #
  #     ###################
  #     ### MY PROGRAMS ###
  #     ###################
  #
  #     # See https://wiki.hyprland.org/Configuring/Keywords/
  #
  #     # Set programs that you use
  #     $terminal = ghostty
  #     $fileManager = thunar
  #     $menu = rofi -show drun
  #     $browser = firefox
  #
  #     #################
  #     ### AUTOSTART ###
  #     #################
  #
  #     # Autostart necessary processes (like notifications daemons, status bars, etc.)
  #     # Or execute your favorite apps at launch like this:
  #
  #     # exec-once = $terminal
  #     # exec-once = nm-applet &
  #     # exec-once = waybar & hyprpaper & firefox
  #     # exec-once = waybar &
  #     exec-once = hyprpaper &
  #     exec-once = swaync &
  #     exec-once = nm-applet --indicator &
  #     exec-once = systemctl --user start plasma-polkit-agent &
  #
  #
  #     #############################
  #     ### ENVIRONMENT VARIABLES ###
  #     #############################
  #
  #     # See https://wiki.hyprland.org/Configuring/Environment-variables/
  #
  #     env = XCURSOR_SIZE,24
  #     env = HYPRCURSOR_SIZE,24
  #
  #
  #     #####################
  #     ### LOOK AND FEEL ###
  #     #####################
  #
  #     # Refer to https://wiki.hyprland.org/Configuring/Variables/
  #
  #     # https://wiki.hyprland.org/Configuring/Variables/#general
  #     general {
  #         gaps_in = 5
  #         gaps_out = 10
  #
  #         border_size = 1
  #
  #         # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
  #         col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
  #         col.inactive_border = rgba(595959aa)
  #
  #         # Set to true enable resizing windows by clicking and dragging on borders and gaps
  #         resize_on_border = false
  #
  #         # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
  #         allow_tearing = false
  #
  #         layout = dwindle
  #     }
  #
  #     # https://wiki.hyprland.org/Configuring/Variables/#decoration
  #     decoration {
  #         rounding = 10
  #
  #         # Change transparency of focused and unfocused windows
  #         active_opacity = 0.95
  #         inactive_opacity = 0.95
  #
  #         shadow {
  #             enabled = true
  #             range = 4
  #             render_power = 3
  #             color = rgba(1a1a1aee)
  #         }
  #
  #         # https://wiki.hyprland.org/Configuring/Variables/#blur
  #         blur {
  #             enabled = true
  #             size = 10
  #             passes = 3
  #             new_optimizations = true
  #             ignore_opacity = true
  #             vibrancy = 0.1696
  #             noise = 0
  #             brightness = 0.9
  #         }
  #     }
  #
  #     # https://wiki.hyprland.org/Configuring/Variables/#animations
  #     animations {
  #         enabled = true
  #
  #         # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
  #
  #         bezier = myBezier, 0.05, 0.9, 0.1, 1.05
  #
  #         animation = windows, 1, 7, myBezier
  #         animation = windowsOut, 1, 7, default, popin 80%
  #         animation = border, 1, 10, default
  #         animation = borderangle, 1, 8, default
  #         animation = fade, 1, 7, default
  #         animation = workspaces, 1, 6, default
  #     }
  #
  #     # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
  #     dwindle {
  #         pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
  #         preserve_split = true # You probably want this
  #     }
  #
  #     # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
  #     master {
  #         new_status = master
  #     }
  #
  #     # https://wiki.hyprland.org/Configuring/Variables/#misc
  #     misc {
  #         force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
  #         disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
  #     }
  #
  #
  #     #############
  #     ### INPUT ###
  #     #############
  #
  #     # https://wiki.hyprland.org/Configuring/Variables/#input
  #     input {
  #         kb_layout = us
  #         kb_variant =
  #         kb_model =
  #         kb_options =
  #         kb_rules =
  #
  #         follow_mouse = 1
  #
  #         sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  #
  #         touchpad {
  #             natural_scroll = false
  #         }
  #     }
  #
  #     # https://wiki.hyprland.org/Configuring/Variables/#gestures
  #     gestures {
  #         workspace_swipe = false
  #     }
  #
  #     # Example per-device config
  #     # See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
  #     device {
  #         name = epic-mouse-v1
  #         sensitivity = -0.5
  #     }
  #
  #
  #     ####################
  #     ### KEYBINDINGSS ###
  #     ####################
  #
  #     # See https://wiki.hyprland.org/Configuring/Keywords/
  #     $mainMod = SUPER # Sets "Windows" key as main modifier
  #
  #     # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
  #     bind = $mainMod, PERIOD, exec, hyprlock
  #     bind = $mainMod, T, exec, $terminal
  #     bind = $mainMod, Q, killactive,
  #     bind = $mainMod, M, exit,
  #     bind = $mainMod, F, fullscreen
  #     bind = $mainMod, E, exec, $fileManager
  #     bind = $mainMod, V, togglefloating,
  #     bindr = $mainMod, $mainMod_L,exec, $menu
  #     bind = $mainMod, P, pseudo, # dwindle
  #     bind = $mainMod, S, togglesplit, # dwindle
  #     bind = $mainMod, B, exec, $browser
  #     bind = $mainMod, G, togglegroup
  #
  #     # Move focus with mainMod + vim keys
  #     bind = $mainMod, h, movefocus, l
  #     bind = $mainMod, l, movefocus, r
  #     bind = $mainMod, k, movefocus, u
  #     bind = $mainMod, j, movefocus, d
  #
  #     # Move window with mainMod + vim keys
  #     bind = $mainMod SHIFT, h, movewindow, l
  #     bind = $mainMod SHIFT, l, movewindow, r
  #     bind = $mainMod SHIFT, k, movewindow, u
  #     bind = $mainMod SHIFT, j, movewindow, d
  #
  #     # Resize window with mainMod + ctrl + vim keys
  #     bind = $mainMod CTRL, h, resizeactive, -50 0
  #     bind = $mainMod CTRL, l, resizeactive, 50 0
  #     bind = $mainMod CTRL, k, resizeactive, 0 -50
  #     bind = $mainMod CTRL, j, resizeactive, 0 50
  #
  #     # Switch workspaces with mainMod + [0-9]
  #     bind = $mainMod, 1, split-workspace, 1
  #     bind = $mainMod, 2, split-workspace, 2
  #     bind = $mainMod, 3, split-workspace, 3
  #     bind = $mainMod, 4, split-workspace, 4
  #     bind = $mainMod, 5, split-workspace, 5
  #     bind = $mainMod, 6, split-workspace, 6
  #     bind = $mainMod, 7, split-workspace, 7
  #     bind = $mainMod, 8, split-workspace, 8
  #     bind = $mainMod, 9, split-workspace, 9
  #     bind = $mainMod, 0, split-workspace, 10
  #
  #     # Move active window to a workspace with mainMod + SHIFT + [0-9]
  #     bind = $mainMod SHIFT, 1, split-movetoworkspacesilent, 1
  #     bind = $mainMod SHIFT, 2, split-movetoworkspacesilent, 2
  #     bind = $mainMod SHIFT, 3, split-movetoworkspacesilent, 3
  #     bind = $mainMod SHIFT, 4, split-movetoworkspacesilent, 4
  #     bind = $mainMod SHIFT, 5, split-movetoworkspacesilent, 5
  #     bind = $mainMod SHIFT, 6, split-movetoworkspacesilent, 6
  #     bind = $mainMod SHIFT, 7, split-movetoworkspacesilent, 7
  #     bind = $mainMod SHIFT, 8, split-movetoworkspacesilent, 8
  #     bind = $mainMod SHIFT, 9, split-movetoworkspacesilent, 9
  #     bind = $mainMod SHIFT, 0, split-movetoworkspacesilent, 10
  #
  #     # Example special workspace (scratchpad)
  #     bind = $mainMod, A, togglespecialworkspace, magic
  #     bind = $mainMod SHIFT, A, movetoworkspace, special:magic
  #
  #     # Scroll through existing workspaces with mainMod + scroll
  #     bind = $mainMod, mouse_down, workspace, e+1
  #     bind = $mainMod, mouse_up, workspace, e-1
  #
  #     # Move/resize windows with mainMod + LMB/RMB and dragging
  #     bindm = $mainMod, mouse:272, movewindow
  #     bindm = $mainMod, mouse:273, resizewindow
  #
  #
  #     ##############################
  #     ### WINDOWS AND WORKSPACES ###
  #     ##############################
  #
  #     # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
  #     # See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
  #
  #     # Example windowrule v1
  #     # windowrule = float, ^(kitty)$
  #
  #     # Example windowrule v2
  #     # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
  #
  #     windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
  #
  #   '';
  # };

  home.packages = with pkgs; [
    tmux
    ghostty
    jetbrains-mono
    nwg-displays
    rofi-wayland
    hyprpaper
    libnotify
    hyprlock
    wl-clipboard
    zoxide
    starship
    pyenv
    libsecret
    # user apps
    steam
    webcord
    # programming
    rustup
    clang
    gnumake
    cmake
  ];

  fonts.fontconfig.enable = true;

  programs.git = {
    enable = true;
    userName = "roberte777";
    userEmail = "rewilkes0041@gmail.com";
    aliases = {
      ci = "commit";
      co = "checkout";
      s = "status";
    };
    extraConfig = {
      credential = {
        credentialStore = "store";
        helper = "store";
      };
    };
  };

  # This value determines the Home Manager release that your
  # configuration is compatible with. This helps avoid breakage
  # when a new Home Manager release introduces backwards
  # incompatible changes.
  #
  # You can update Home Manager without changing this value. See
  # the Home Manager release notes for a list of state version
  # changes in each release.
  home.stateVersion = "24.11";

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;
}
